baseURL = "https://hackfight.dev"
languageCode = 'en'
title = 'HackFight.dev'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  name = "HackFight"
  location = "Switzerland"
  description = "A young game developer interested in low level and VR."
  profile_image = "/images/hatsune_miku.jpg"

  # Social and contact information
  email = "contact@hackfight.dev"
  github = "https://github.com/hackfight"
  github_username = "HackFight"
  discord = "HackFight"
  youtube = "https://www.youtube.com/@HackFight"
  youtube_username = "HackFight"
  bluesky = "https://bsky.app/profile/hackfight.bsky.social"
  bluesky_username = "hackfight.bsky.social"
  instagram = "https://instagram.com/haccfight"
  instagram_username = "HaccFight"
  tiktok = "https://www.tiktok.com/@haccfight"
  tiktok_username = "HaccFight"
  modrinth = "https://modrinth.com/user/HackFight"
  modrinth_username = "HackFight"
  planet_minecraft = "https://www.planetminecraft.com/member/hackfight"
  planet_minecraft_username = "HackFight"
  itchio = "https://hackfight.itch.io"
  itchio_username = "HackFight"

[languages]
  [languages.en]
    languageName = "English"
    title = "HackFight.dev"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        pageRef = "/"
        weight = 1
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about" # Corresponds to content/en/about.md or content/en/about/_index.md
        weight = 2
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 3
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 4
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 5
      [[languages.en.menu.main]]
        name = "Socials"
        pageRef = "/socials"
        weight = 6
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 7

  [languages.fr]
    languageName = "Français"
    title = "HackFight.dev"
    weight = 2
    contentDir = "content/fr"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "Accueil"
        pageRef = "/"
        weight = 1
      [[languages.fr.menu.main]]
        name = "À Propos"
        pageRef = "/about"
        weight = 2
     [[languages.fr.menu.main]]
       name = "Expérience"
       pageRef = "/experience"
       weight = 3
      [[languages.fr.menu.main]]
        name = "Projets"
        pageRef = "/projects"
        weight = 4
      [[languages.fr.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 5
      [[languages.fr.menu.main]]
        name = "Réseaux"
        pageRef = "/socials"
        weight = 6
      [[languages.fr.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 7